### ISSUE TITLE
Support for a list of KUBECONFIG files

### ISSUE THREAD

**Issue by webframp** [chrisbarrett/kubernetes-el#101]
According to https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable a list of files is supported.

Is using a list for this value supported?

**Comment by FalyPr1nc3** [comment]
Have you tried?
Based on my experience it works.
It seems this package just uses kubectl as a back-end and you can expect that KUBECONFIG affects this package the same way it affects kubectl.

**Comment by webframp** [comment]
Yea, adjusted my config a bit while debugging. Seems like my ENV wasn't getting populated correctly but it appears to be working now.
