### ISSUE TITLE
Are there plans to cut a new release?

### ISSUE THREAD

**Issue by kat-co** [chrisbarrett/kubernetes-el#102]
It looks like the last stable release was in 2017. It also looks like there hasn't been too much activity on the project since, but I was wondering if you all are working towards a new stable release?

**Comment by chrisbarrett** [comment]
Hey there! Thanks for the very reasonable question.

My current employer isn't using k8s and my spare time isn't going into open source these days. It'll get some love if this situation changes. :)

**Comment by noorul** [comment]
@chrisbarrett Can you share the steps to cut a release?

**Comment by chrisbarrett** [comment]
In terms of actually doing the release, it should be a matter of cloning the repo and running `make release`.

**Comment by noorul** [comment]
Released 0.13.0
