### ISSUE TITLE
Remove unnecessary (and recently broken) references to `magit-highlight-region`, `magit-unhighlight-region`

### ISSUE THREAD

**Issue by fritzgrabo** [chrisbarrett/kubernetes-el#116]
`magit-highlight-region` and `magit-unhighlight-region` are [referenced in the definition of `kubernetes-mode`](https://github.com/chrisbarrett/kubernetes-el/blob/master/kubernetes-modes.el#L82-L83). However, both of these functions were recently renamed in https://github.com/magit/magit/commit/e4b64972047ad31d5f44200e4c1656d54067e1b. Consequently, if you're using `kubernetes-el` with a recent version of `magit`, you'll see a ton of these messages:

```
redisplay--pre-redisplay-functions: (void-function magit-unhighlight-region)
```

Note that the new names of these functions (`magit-section--{un,}highlight-region`) indicate that they [should not be used outside of magit](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html), really. Also note that at first glance, it seems like these functions only handle the edge case of sections with diff hunks in them, but fallback to the default values of `redisplay-{un,}highlight-region-function` in all other cases.

So while it's certainly possible to just update the definition of `kubernetes-mode` to use the new names, I think it makes more sense to just remove the related settings there altogether.

I've tested ^^ locally and didn't find any issues with that.

Happy to submit a PR; please let me know if I'm missing something.

**Comment by noorul** [comment]
@fritzgrabo  Please submit a PR.

**Comment by fritzgrabo** [comment]
Thanks!
