### ISSUE TITLE
Support users who cannot list secrets

### ISSUE THREAD

**Issue by mar-kolya** [chrisbarrett/kubernetes-el#126]
Currently default overview view tries to list secrets. There are cases when kubectl user cannot do that. Currently an error is displayed in the bottom and this makes usage hard.

Instead it may be more useful to display error (or warning) in secrets section of the overview.
It looks like similar strategy could apply to any section, actually.

**Comment by themmes** [comment]
I have this problem, I have actually no access to our `default` namespace, however due to all the errors popping up I am unable to switch to any other namespace...

**Comment by EgorDuplensky** [comment]
I have the same issue with nodes. If user has no access to "get nodes" api, then overview buffer is almost unusable because of errors. Perhaps the list of k8s resources to interact with should be configurable.

**Comment by autoluminescent** [comment]
I have the same issue as @EgorDuplensky. I have defined a custom view without nodes (`kubernetes-overview-custom-views-alist`), which I use as my default view (`kubernetes-default-overview-view`), and was hoping that might stop `kubernetes-el` from attempting to update unused resources, but no dice. Would it make sense to update only the resources that are configured in the currently used view?

**Comment by noorul** [comment]
Closing the issue as this can be solved by using kubernetes-overview-custom-views-alist
