### ISSUE TITLE
Generic handling of resources

### ISSUE THREAD

**Issue by nightscape** [chrisbarrett/kubernetes-el#129]
Hi @chrisbarrett @noorul,

I just found and immediately ❤️  this project (big magit fan as well)!
In a current project, I have a lot of CRDs, some from Istio, others from specialized operators.
I was wondering if it is possible to create rather generic code to deal with all of them.
The Kubernetes API itself is very uniform and you have mostly the same operations (get, describe, delete) that can be applied to all resources.
I've seen the code does special handling for every resource type.
Is there an underlying reason for this that would byte me were I to write such a CRD handler?

**Comment by chrisbarrett** [comment]
Hey there! The display logic is tailored to having quite customised views for different resource types. But if a generic view is appropriate for inspecting custom resources then I say go for it!

**Comment by nightscape** [comment]
I just discovered [kubel](https://github.com/abrochard/kubel), another Kubernetes package for Emacs which is able to display all resources. This and kubernetes-el together provide everything I need.
Thanks for your quick answer @chrisbarrett
