### ISSUE TITLE
pod-view-detail should show name-image pairs of all containers in pod

### ISSUE THREAD

**Issue by jinnovation** [chrisbarrett/kubernetes-el#133]
Currently the `pod-view-detail` AST component is implemented to only show the name and image of the first container that appears in `containerStatuses`. This results in misleading display of pod details for pods running multiple containers, as only one container's name and image are displayed:
```
POD_NAME                  Running      2/2          0    10d
  Name:       CONTAINER_0_NAME
  Namespace:  kubeflow
  Image:      CONTAINER_0_IMAGE
  Host IP:    10.202.56.91
  Pod IP:     10.202.78.194
  Started:    2021-04-29T12:26:05Z
```

Rather, it would be more reflective to have the pod view details display the name-image pairs of *all* containers running on that pod, maybe like so:
```
POD_NAME                  Running      2/2          0    10d
  Namespace:  kubeflow
  Host IP:    10.202.56.91
  Pod IP:     10.202.78.194
  Started:    2021-04-29T12:26:05Z
  Containers:
    - Name:   CONTAINER_0_NAME
      Image:  CONTAINER_0_IMAGE

    - Name:   CONTAINER_1_NAME
      Image:  CONTAINER_1_IMAGE

    ...
```

**Comment by jinnovation** [comment]
@noorul: might be fun. I was looking at the AST code last night while figuring out the underlying issue here, so a PR would be a natural extension of that.

No guarantees on ETA, of course.

**Comment by noorul** [comment]
Thank @jinnovation
