### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by jinnovation** [chrisbarrett/kubernetes-el#144]
`travis-ci.org` will be shutting down at the end of May, after which builds might still run indefinitely on`.org`, but that is not a promise.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/1932579/120000515-e4d88600-bfa0-11eb-867b-ca3635d532f3.png">

Travis recommends migrating to `travis-ci.com` and gives [some high-level guidance here](https://blog.travis-ci.com/2021-05-07-orgshutdown).

**Comment by jinnovation** [comment]
I personally don't have an opinion here. 

That said, if the project's current Travis configuration is tied to @chrisbarrett's personal account or anything along those lines (I haven't had occasion to use Travis in a meaningful capacity, so I'm unsure of the specifics of how setup works) , that might make this a good time to migrate to GitHub Actions, which I'm guessing would be simply tied to the repo itself.

**Comment by noorul** [comment]
@jinnovation  Exactly, migrating to travis.com is not that straightforward.

**Comment by jinnovation** [comment]
Ah, I see. In that case, I think Github Actions is as good an alternative as any.

**Comment by jinnovation** [comment]
Similarly, Steve Purcell—the author of `nix-emacs-ci` that our CI is based on—has written a helpful [Github Action entrypoint](https://github.com/marketplace/actions/set-up-emacs) that we can take advantage of as well.

**Comment by jinnovation** [comment]
Likewise, for Cask install: [the `Setup Cask` action](https://github.com/marketplace/actions/setup-cask) looks promising.
