### ISSUE TITLE
Implement support for replication controllers

### ISSUE THREAD

**Issue by noorul** [chrisbarrett/kubernetes-el#29]

**Comment by chrisbarrett** [comment]
Sure, I can look at that. We don't use them in our setup out work, so you can help by sending me a sample JSON output from kubectl (with IPs zeroed out, and any other sensitive info obfuscated).

I would want the output from the following command:

```
kubectl get rc -o json
```

**Comment by chrisbarrett** [comment]
FYI we use deployments at Movio, so right now most of my love is going toward that resource type :)

**Comment by noorul** [comment]
@chrisbarrett At work we also switched to deployments. So closing this issue.
