### ISSUE TITLE
kubernetes-use-context moves point in current buffer

### ISSUE THREAD

**Issue by svend** [chrisbarrett/kubernetes-el#41]
Thanks for your work on kubernetes-el!

Calling `kubernetes-use-context` outside of kubernetes-overview causes the point in the current buffer to move to the start of the buffer. To reproduce:

- Open a buffer
- Move point to end of the buffer
- `M-x kubernetes-use-context`
- Select a context
- Point is moved to the beginning of the buffer

**Comment by chrisbarrett** [comment]
Good catch. Thanks for the report!
