### ISSUE TITLE
`kubernetes-overview` errors on contexts without a namespace

### ISSUE THREAD

**Issue by svend** [chrisbarrett/kubernetes-el#43]
The contexts in my .kube/config do not have a namespace specified. This results in the following error when calling `kubernetes-overview`:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  propertize(nil face kubernetes-namespace)
  kubernetes-contexts--render-current-context(((name . "minikube") (context (cluster . "minikube") (user . "team"))) nil)
```

kubectl uses the default namespace for these contexts. Perhaps kubernetes-el could use the same default?

**Comment by chrisbarrett** [comment]
Thanks for the report. 👍 

I think this is just a rendering issue, so I'll tweak it not to expect the namespace be set when rendering the current context.

**Comment by chrisbarrett** [comment]
This should be fixed, but let me know if you encounter this problem anywhere else.
