### ISSUE TITLE
kubernetes-refresh too many open files

### ISSUE THREAD

**Issue by noorul** [chrisbarrett/kubernetes-el#6]
Error running timer ‘kubernetes-refresh’: (file-error "Creating pipe" "Too many open files") [3 times]
Error running timer ‘kubernetes-refresh’: (file-error "Opening pty" "Too many open files")
Error running timer ‘kubernetes-refresh’: (file-error "Creating pipe" "Too many open files") [22 times]
Error running timer ‘persistent-scratch-save’: (file-error "Opening output file" "Too many open files" "/Users/nislam/.emacs.d/data/.persistent-scratch.new")
Error running timer ‘kubernetes-refresh’: (file-error "Creating pipe" "Too many open files") [60 times]
Error running timer ‘persistent-scratch-save’: (file-error "Opening output file" "Too many open files" "/Users/nislam/.emacs.d/data/.persistent-scratch.new")
Error running timer ‘kubernetes-refresh’: (file-error "Creating pipe" "Too many open files") [36 times]

**Comment by chrisbarrett** [comment]
Please see if you can reproduce this on HEAD. I've changed the subprocess handling to more aggressively clean up resources.

**Comment by noorul** [comment]
Yesterday, I used HEAD and I confirm that things look ok
