### ISSUE TITLE
Implement support for openshift

### ISSUE THREAD

**Issue by iocanel** [chrisbarrett/kubernetes-el#65]
If used against openshift you may hit the following error:

    
    Error from server (Forbidden): User "iocanel" cannot list all namespaces in the cluster

which is a result of using: 

     kubectl get namespaces -o json --namespace=syndesis-ci

I think that for openshift it would make more sense to use something like:

    oc get projects -o json --namespace=syndesis-ci

**Comment by chrisbarrett** [comment]
Thanks for reporting. I've never used openshift and have no plans to, so it's out of the scope of this project right now. :)

**Comment by iocanel** [comment]
@chrisbarrett: Would you accept a PR that would add support for it?

**Comment by chrisbarrett** [comment]
I really appreciate the offer. I wouldn't want to support Openshift right now--I wouldn't be able to support it well on an ongoing basis. My priority with this project right now is the rewrite on the develop branch, which is where I'd rather put my focus. :)
