### ISSUE TITLE
Can't see logs of pod with multiple containers

### ISSUE THREAD

**Issue by epeld** [chrisbarrett/kubernetes-el#66]
Hi!
I'm trying to view the logs of a pod with two containers and it is giving me the same error you would get if you did `kubectl logs mypod` instead of `kubectl logs mypod mycontainer`

    Error from server (BadRequest): the server rejected our request for an unknown reason (get pods mypod)

    Process kubernetes-exec exited abnormally with code 1

is there a way of working around this?

Steps to reproduce: 
1. `M-x kubernetes-overview`
2. `<type 'l' as in logs>`
3. `<enter pod name>`
4. `ERROR!`.

Thanks!

**Comment by chrisbarrett** [comment]
Hey there. Thanks for reporting. I can't think of a way to work around this given what's currently implemented, but I'll add it to the todo-list.

**Comment by chrisbarrett** [comment]
I don't have much time to do open source at the mo. Pull requests welcome.

**Comment by tazjin** [comment]
@epeld @dod38fr If you guys still need this - I've opened a PR (see above) that implements a potential solution. Feel free to test it!
