### ISSUE TITLE
Commands should take object at point as default

### ISSUE THREAD

**Issue by matthew-piziak** [chrisbarrett/kubernetes-el#67]
For example, `l l` (that is, `kubernetes-logs-fetch-all`) asks the user to select a pod. But it should default the pod under point, like Magit does.

**Comment by matthew-piziak** [comment]
Thank you for this package, by the way. It makes working with Kubernetes _much_ more pleasant.

**Comment by noorul** [comment]
I am not facing this issue. From which display are you pressing 'l'? If you press 'l' outside of pods context you will be prompted with a list of pods, but if you are really in pod view and do this, you should not be prompted.

**Comment by matthew-piziak** [comment]
Interesting! I can reproduce this issue from `*kubernetes overview*` and `*kubernetes pod*`.

I am using package version `20170523.1517` and Emacs version `27.0.50`.

**Comment by matthew-piziak** [comment]
Aha! But if I press `v` for `kubernetes-overview-set-sections` and then select `pods`, then the behavior is as you describe it. Thank you!

**Comment by matthew-piziak** [comment]
I will close this issue for now, since I'm sure this will be documented at some point when the package is more mature. Thank you again for your hard work!
